apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: details
  namespace: bookinfo
spec:
  service: details
  backends:
    - service: details
      weight: 250
    - service: details.bookinfo.global
      weight: 250