apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: reviews
spec:
  service: reviews.bookinfo.svc.cluster.local
  backends:
    - service: reviews.bookinfo.svc.cluster.local
      weight: 250
    - service: reviews-v2.bookinfo.svc.cluster.local
      weight: 250
    - service: reviews-v3.bookinfo.svc.cluster.local
      weight: 250