---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: productpage-reviews
  namespace: bookinfo
destination:
  kind: ServiceAccount
  name: bookinfo-reviews
  namespace: bookinfo
specs:
  - kind: HTTPRouteGroup
    name: bookinfo-allowed-paths
    matches:
      - api
sources:
  - kind: ServiceAccount
    name: bookinfo-productpage
    namespace: bookinfo
---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: reviews-ratings
  namespace: bookinfo
destination:
  kind: ServiceAccount
  name: bookinfo-ratings
  namespace: bookinfo
specs:
  - kind: HTTPRouteGroup
    name: bookinfo-allowed-paths
    matches:
      - api
sources:
  - kind: ServiceAccount
    name: bookinfo-reviews
    namespace: bookinfo