apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: {{ .VirtualServiceName }}
  namespace: {{ .Namespace }}
spec:
  sslConfig:
    secretRef:
      name: {{ .Domain }}
      namespace: {{ .Namespace }}
    sniDomains:
      - {{ .Domain }}
  virtualHost:
    domains:
      - {{ .Domain }}
    routes:
      - matcher:
          prefix: /
        routeAction:
          single:
            upstream:
              name: {{ .UpstreamName }}
              namespace: {{ .UpstreamNamespace }}