apiVersion: marketplace.solo.io/v1
kind: ApplicationState
metadata:
  name: bookinfo-demo
  namespace: sm-marketplace
spec:
  applicationName: bookinfo
  applicationSpec:
    flavors:
      - description: Install bookinfo
        name: default
    manifestsArchive:
      uri: https://storage.googleapis.com/sm-marketplace-registry/bookinfo.tar.gz
    version: 1.13.0
  displayName: bookinfo
  installationState:
    flavorName: default
    installNamespace: bookinfo
    mesh:
      name: istio-istio-system
      namespace: sm-marketplace
    version: 1.13.0
  registryName: hub-demos